version: "3"
services:
  server:
    container_name: quiz-server
    build: .
    ports:
      - "8080:8080"
    networks:
      - quiz

  cli:
    container_name: quiz-client
    restart: always
    build:
      context: ./cmd
      dockerfile: Dockerfile
    networks:
      - quiz

networks:
  quiz:
    driver: bridge

