version: "3"
services:
  server:
    container_name: quiz-server
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    networks:
      - quiz

  cli:
    container_name: quiz-client
    build:
      context: ./cmd
      dockerfile: Dockerfile
    networks:
      - quiz

networks:
  quiz:
