mode: "dev"
dotenv: ".env/dev"

server:
  addr: "localhost"
  port: "8080"
  write_timeout: 20s
  read_timeout: 20s
  idle_timeout: 20s
  graceful_timeout: 20s
cli:
  addr: "localhost"
  port: "4040"
pprof:
  addr: "localhost"
  port: "5050"
