mode: "dev"
dotenv: ".env/dev"

server:
  addr: "localhost"
  port: "8080"
  write_timeout: 100s
  read_timeout: 100s
  idle_timeout: 100s
  graceful_timeout: 100s
cli:
  addr: "localhost"
  port: "4040"
pprof:
  addr: "localhost"
  port: "5050"
